/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Someone-PC
 */
public class ViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewAdmin
     */
    public ViewAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddPetugas = new javax.swing.JButton();
        btnAddPenyedia = new javax.swing.JButton();
        btnAddGudang = new javax.swing.JButton();
        btnRPetugas = new javax.swing.JButton();
        btnRPenyedia = new javax.swing.JButton();
        btnRGudang = new javax.swing.JButton();
        btnEditGudang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logout.setText("Log Out");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddPetugas.setText("Add Petugas");

        btnAddPenyedia.setText("Add Penyedia");
        btnAddPenyedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPenyediaActionPerformed(evt);
            }
        });

        btnAddGudang.setText("Add Gudang");

        btnRPetugas.setText("Remove Petugas");
        btnRPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPetugasActionPerformed(evt);
            }
        });

        btnRPenyedia.setText("Remove Penyedia");
        btnRPenyedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPenyediaActionPerformed(evt);
            }
        });

        btnRGudang.setText("Remove Gudang");

        btnEditGudang.setText("Edit Gudang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAddPenyedia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRPenyedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRGudang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRPetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(btnEditGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)))
                    .addContainerGap()))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddGudang, btnAddPenyedia, btnAddPetugas});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(btnRPenyedia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRPetugas)
                            .addGap(18, 18, 18)
                            .addComponent(btnRGudang))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAddPenyedia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(btnAddPetugas)
                            .addGap(18, 18, 18)
                            .addComponent(btnAddGudang)))
                    .addGap(18, 18, 18)
                    .addComponent(btnEditGudang)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddGudang, btnAddPenyedia, btnAddPetugas});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditGudang, btnRGudang, btnRPenyedia, btnRPetugas});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPenyediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPenyediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPenyediaActionPerformed

    private void btnRPenyediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPenyediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRPenyediaActionPerformed

    private void btnRPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public JButton getBtnAPenyedia() {
        return btnAddPenyedia;
    }
    
    public JButton getBtnAPetugas() {
        return btnAddPetugas;
    }
    
    public JButton getBtnAGudang() {
        return btnAddGudang;
    }
    
    public JButton getBtnRPenyedia() {
        return btnRPenyedia;
    }
    
    public JButton getBtnRPetugas() {
        return btnRPetugas;
    }
    
    public JButton getBtnRGudang() {
        return btnRGudang;
    }
    
    public JButton getBtnEGudang() {
        return btnEditGudang;
    }

    public JButton getBtnLogout() {
        return logout;
    }
    
    public void addListener(ActionListener e) {
        btnAddGudang.addActionListener(e);
        btnAddPenyedia.addActionListener(e);
        btnAddPetugas.addActionListener(e);
        btnEditGudang.addActionListener(e);
        btnRGudang.addActionListener(e);
        btnRPenyedia.addActionListener(e);
        btnRPetugas.addActionListener(e);
        logout.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGudang;
    private javax.swing.JButton btnAddPenyedia;
    private javax.swing.JButton btnAddPetugas;
    private javax.swing.JButton btnEditGudang;
    private javax.swing.JButton btnRGudang;
    private javax.swing.JButton btnRPenyedia;
    private javax.swing.JButton btnRPetugas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
