/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DB.Database;
import Model.AplikasiInventaris;
import Model.Barang;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Riri
 */
public class ViewPetugasLihatBarang extends javax.swing.JFrame {

    /**
     * Creates new form ViewPetugasLihatBarang
     */
    public ViewPetugasLihatBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarangGudang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKembali.setText("Kembali");

        TableBarangGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Gudang", "ID Barang", "Nama Barang", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(TableBarangGudang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 443, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public void addListener(ActionListener e) {
        btnKembali.addActionListener(e);
    }
    
    public void setTableMenu(){
        String s=null;
        app.getArray();
        TableBarangGudang.setSize(100, 100);
        for(int i=0; i<app.ListBrg.size(); i++){
            TableBarangGudang.setValueAt(app.ListGudang.get(i).getIdGudang(), i, 0);
            TableBarangGudang.setValueAt(app.ListBrg.get(i).getIdBarang(), i, 1);
            TableBarangGudang.setValueAt(app.ListBrg.get(i).getNamaBarang(), i, 2);
            TableBarangGudang.setValueAt(app.ListBrg.get(i).getStock(), i, 3);
        }
    }
    
    private AplikasiInventaris app = new AplikasiInventaris();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBarangGudang;
    private javax.swing.JButton btnKembali;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
